// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/colin-axner/sangam/dns/keeper/
// ALIASGEN: github.com/colin-axner/sangam/dns/types/
package dns

import (
	"github.com/colin-axner/sangam/dns/keeper/"
	"github.com/colin-axner/sangam/dns/types/"
)

type (
	Keeper            = keeper.Keeper
	Entry             = types.Entry
	MsgPreCommitEntry = types.MsgPreCommitEntry
	MsgCommitEntry    = types.MsgCommitEntry
	Path              = types.Path
)
