// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/AdityaSripal/sangam/dns/types
// ALIASGEN: github.com/AdityaSripal/sangam/dns/keeper
package dns

import (
	"github.com/AdityaSripal/sangam/dns/keeper"
	"github.com/AdityaSripal/sangam/dns/types"
)

const (
	PreCommitSequence     = types.PreCommitSequence
	CommitSequence        = types.CommitSequence
	ModuleName            = types.ModuleName
	StoreKey              = types.StoreKey
	RouterKey             = types.RouterKey
	QuerierRoute          = types.QuerierRoute
	TypeMsgPreCommitEntry = types.TypeMsgPreCommitEntry
	TypeMsgCommitEntry    = types.TypeMsgCommitEntry
)

var (
	// functions aliases
	RegisterCodec        = types.RegisterCodec
	SetModuleCodec       = types.SetModuleCodec
	StringToDomain       = types.StringToDomain
	NewMsgPreCommitEntry = types.NewMsgPreCommitEntry
	NewMsgCommitEntry    = types.NewMsgCommitEntry

	// variable aliases
	ModuleCdc              = types.ModuleCdc
	ErrInvalidOwners       = types.ErrInvalidOwners
	ErrInvalidContentHash  = types.ErrInvalidContentHash
	ErrInvalidHash         = types.ErrInvalidHash
	ErrInvalidContentName  = types.ErrInvalidContentName
	ErrInvalidDomainString = types.ErrInvalidDomainString
	ErrEntryNotFound       = types.ErrEntryNotFound
	ErrHashDoesNotMatch    = types.ErrHashDoesNotMatch
)

type (
	Domain            = types.Domain
	Entry             = types.Entry
	MsgPreCommitEntry = types.MsgPreCommitEntry
	MsgCommitEntry    = types.MsgCommitEntry
	Keeper            = keeper.Keeper
)
